apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: my-folder
  namespace: default
  labels:
    dashboards: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
